epoch: 100

LearningRate:
  base_lr: 0.001
  schedulers:
  - !CosineDecay
    max_epochs: 100
    use_warmup: True
  - !LinearWarmup
    start_factor: 0.
    steps: 2000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2
